version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    expose:
      - "80"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
