// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Evaluations.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("score");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id")
                        .HasName("pk_evaluations");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_evaluations_resume_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_evaluations_status_id");

                    b.HasIndex("VacancyId")
                        .HasDatabaseName("ix_evaluations_vacancy_id");

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("Domain.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Domain.Statuses.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_statuses");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Vacancies.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("education");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("experience");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("uuid")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_vacancies");

                    b.HasIndex("RecruiterId")
                        .HasDatabaseName("ix_vacancies_recruiter_id");

                    b.ToTable("vacancies", (string)null);
                });

            modelBuilder.Entity("Domain.VacancySkills.VacancySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasColumnName("experience");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasColumnName("level");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("vacancy_id");

                    b.Property<Guid?>("VacancyId1")
                        .HasColumnType("uuid")
                        .HasColumnName("vacancy_id1");

                    b.HasKey("Id")
                        .HasName("pk_vacancy_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_vacancy_skills_skill_id");

                    b.HasIndex("VacancyId")
                        .HasDatabaseName("ix_vacancy_skills_vacancy_id");

                    b.HasIndex("VacancyId1")
                        .HasDatabaseName("ix_vacancy_skills_vacancy_id1");

                    b.ToTable("vacancy_skills", (string)null);
                });

            modelBuilder.Entity("Domain.Evaluations.Evaluation", b =>
                {
                    b.HasOne("Domain.Resumes.Resume", "Resume")
                        .WithMany("Evaluations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_resume_id");

                    b.HasOne("Domain.Statuses.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_status_id");

                    b.HasOne("Domain.Vacancies.Vacancy", "Vacancy")
                        .WithMany("Evaluations")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_vacancy_id");

                    b.Navigation("Resume");

                    b.Navigation("Status");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.HasOne("Domain.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Vacancies.Vacancy", b =>
                {
                    b.HasOne("Domain.Users.User", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vacancies_users_id");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("Domain.VacancySkills.VacancySkill", b =>
                {
                    b.HasOne("Domain.Skills.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vacancy_skills_skill_id");

                    b.HasOne("Domain.Vacancies.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vacancy_skills_vacancy_id");

                    b.HasOne("Domain.Vacancies.Vacancy", null)
                        .WithMany("VacancySkills")
                        .HasForeignKey("VacancyId1")
                        .HasConstraintName("fk_vacancy_skills_vacancies_vacancy_id1");

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Domain.Resumes.Resume", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Domain.Vacancies.Vacancy", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("VacancySkills");
                });
#pragma warning restore 612, 618
        }
    }
}
