name: Deploy ASP.NET App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: Secrets

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/evalix-app"

      - name: Run Docker Compose on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/evalix-app
            sudo systemctl stop nginx
            docker-compose down
            docker-compose up --build -d
